# Generated by Django 5.2.10 on 2026-02-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
