# Generated by Django 5.2.10 on 2026-02-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_event_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
