# Generated by Django 5.2.10 on 2026-02-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff_code',
        ),
    ]
